### ISSUE TITLE
How to run the .exe ?

### ISSUE THREAD

**Issue by nicolasplanchon** [AndMu/YiScanner#1]
Hi there,
A huge thank's for your work!

I'm just not sure to understand everything in the way it works.

When I run the .exe, a command prompt pops up ... and disappears in a while :(

In the log I have:

2017-11-26 15:26:59.6818 [Program] [1] INFO Starting 1.0.25.0 version utility...
2017-11-26 15:26:59.7808 [Program] [1] WARN Please specify arguments

Do u know what it means ? Is there anything wrong in my settings ?
In the host parameter I'm to write the IP address of my computer, right ?

Thanks in advance,
Nicolas.

**Comment by AndMu** [comment]
Example of argument 
Wikiled.YiScanner.exe Monitor -Cameras=1080i -Hosts=192.168.0.202 -Out=c:\out -Scan=10

Hosts - IP address  or host name (if you have it) of **camera**

**Comment by AndMu** [comment]
maybe it is confusing, but Cameras option is just to have friendly name of camera.

**Comment by nicolasplanchon** [comment]
oh okep lovely !

Do you know why the .exe closes on the spot after opening?

**Comment by AndMu** [comment]
Is it with monitor option or download? Can you attach log file?

**Comment by nicolasplanchon** [comment]
The .exe closes on the spot so I can't load any command line.

In the log I have:

2017-11-26 15:26:59.6818 [Program] [1] INFO Starting 1.0.25.0 version utility...
2017-11-26 15:26:59.7808 [Program] [1] WARN Please specify arguments


I have to type the command line after the .exe opening or in the parameter ?

**Comment by AndMu** [comment]
If you can't figure out how to specify arguments, I would recommend downloading latest version https://github.com/AndMu/YiScanner/releases/tag/1.1.1
In it, configuration can be done in file 

## Configuration via service.json
In this mode, application will monitor designated cameras

```
"Scan": 30,
"Cameras": "1080i,720p",
"Hosts": "192.168.0.103,192.168.0.129",
"Compress": false,
"Archive": 2,
"Out": "D:/Cloud/Camera/Monitor"
```

**Comment by nicolasplanchon** [comment]
This sounds fucking perfect! :)


Nicolas.

________________________________
De : Andrius Mudinas <notifications@github.com>
Envoyé : lundi 27 novembre 2017 13:02:52
À : AndMu/YiScanner
Cc : PLANCHON Nicolas; Author
Objet : Re: [AndMu/YiScanner] How to run the .exe ? (#1)


If you can't figure out how to specify arguments, I would recommend downloading latest version https://github.com/AndMu/YiScanner/releases/tag/1.1.1
In it, configuration can be done in file

Configuration via service.json

In this mode, application will monitor designated cameras

"Scan": 30,
"Cameras": "1080i,720p",
"Hosts": "192.168.0.103,192.168.0.129",
"Compress": false,
"Archive": 2,
"Out": "D:/Cloud/Camera/Monitor"
