### ISSUE TITLE
How to have still the same output file name ?

### ISSUE THREAD

**Issue by nicolasplanchon** [AndMu/YiScanner#10]
Hi there,
Everything is in the question: in order to be able to run sthg in a way like 'python program.py image.jpg' downloaded images must still have the same name (and replace the former one) or the argument must be automatically updated, do you know how I can manage to do this please ? :)

Best regards,
Nicolas.

**Comment by AndMu** [comment]
It does support automatic name resolution. In your case replace "Cmd": "python program.py %1",

**Comment by nicolasplanchon** [comment]
The %1 is necessary to have the automatic name resolution or must be changed ?


Nicolas.

________________________________
De : Andrius Mudinas <notifications@github.com>
Envoyé : lundi 22 janvier 2018 16:19:47
À : AndMu/YiScanner
Cc : PLANCHON Nicolas; Author
Objet : Re: [AndMu/YiScanner] How to have still the same output file name ? (#10)


It does support automatic name resolution. In your case replace "Cmd": "python program.py %1",

**Comment by AndMu** [comment]
%1 is file marker. It is necesary if you want to include actual file name.

**Comment by nicolasplanchon** [comment]
So I have just to modify the name of program.py right ?

**Comment by AndMu** [comment]
You should insert into service.json:

"Action":{
    "Type": "Execute",
    "Cmd": "python program.py %1",
    "Payload": null
    }
