### ISSUE TITLE
How to use Action to run windows copy?

### ISSUE THREAD

**Issue by ianrathbone** [AndMu/YiScanner#13]
Hi apologies if I'm missing something - I'm trying to figure out how to run a windows copy on each file using the action param:

https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/copy

Tried this:
"Cmd": "cmd.exe copy /y %1 C:\destination\analysis.mp4"

However the windows service falls over when starting up

**Comment by AndMu** [comment]
Please replace backslash with a forward slash
\ with /

**Comment by ianrathbone** [comment]
Thanks @AndMu that has sorted the startup issue - do you know if the copy or xcopy commands will work ok with the action param? As I'm not seeing the above work...

**Comment by ianrathbone** [comment]
@AndMu understand the problem now - looks like Windows is a little fussy with the formatting of the filename that's coming through to the command - having a combination of forward and back slashes!! I've applied a tweak on my command to run a batch file which in turn fixes the slashes. Now working ;)

**Comment by AndMu** [comment]
That is not a windows problem per se, but more JSON (configuration file) text format. To write backslash, you should use \\. Windows accept both.
https://www.freeformatter.com/json-escape.html
