### ISSUE TITLE
Download mode

### ISSUE THREAD

**Issue by insane78** [AndMu/YiScanner#15]
YiScanner download only the current daily recorded video file. It would be awesome if i can schedule a interval of 2 hours (for example) and the service download all videos recorded from last run (2 hours ago). I need yiscanner only to use it such as backup of the sd cards.

**Comment by AndMu** [comment]
Maybe I don't understand the question, but you can already run at any interval as a service, which should fulfill your requirement.

**Comment by insane78** [comment]
I would like that:
- in config i set the interval to 2 hours
- start the service and it download last 2 hours of recording for all cams i configured via ftp.
- after 2 hours the service download all videos of last 2 hours and so on...

Now, if i understand, the service download only the videos recorded after his start time.

**Comment by insane78** [comment]
I undesrtood now... like suggested in main page, i used the exe with command line missing the interval value and works like a charm. Now i can schedule this process and download all videos.

**Comment by AndMu** [comment]
Cool. As I thought that is supported already.
