### ISSUE TITLE
How to download images rather videos ?

### ISSUE THREAD

**Issue by nicolasplanchon** [AndMu/YiScanner#2]
Hi there,
I have just a little question:

To echo my other thread https://github.com/shadow-1/yi-hack-v3/issues/89 I wish I could download images rather than videos in order to process machine learning algorithms after this.

Do you know in what way I can use your script to check and download new thumbnail images from the motion detector rather than videos please ? :) 

Thank's,
Nicolas.

**Comment by AndMu** [comment]
I will add that in next version.

**Comment by nicolasplanchon** [comment]
Amazing ! When do you think to be able to release this new version ? :)

________________________________
De : Andrius Mudinas <notifications@github.com>
Envoyé : jeudi 7 décembre 2017 01:25:24
À : AndMu/YiScanner
Cc : PLANCHON Nicolas; Author
Objet : Re: [AndMu/YiScanner] How to download images rather videos ? (#2)


I will add that in next version.

**Comment by AndMu** [comment]
Released 1.2.14 version which supports images (first frame)
To use configuration option - "Images": true,

https://github.com/AndMu/YiScanner/releases/tag/1.2.14

**Comment by nicolasplanchon** [comment]
Awesome !


A huge thanks !

________________________________
De : Andrius Mudinas <notifications@github.com>
Envoyé : vendredi 8 décembre 2017 01:01:33
À : AndMu/YiScanner
Cc : PLANCHON Nicolas; Author
Objet : Re: [AndMu/YiScanner] How to download images rather videos ? (#2)


Released 1.2.14 version which supports images (first frame)
To use configuration option - "Images": true,

https://github.com/AndMu/YiScanner/releases/tag/1.2.14
