### ISSUE TITLE
How to use YiScanner.1.2.14?

### ISSUE THREAD

**Issue by Deee46** [AndMu/YiScanner#3]
need help, can anyone tell me how to use this quickly? i tried reading the readme but when i ran the "Wikiled.YiScanner.exe" by double clicking it it just opens a black screen..

i did edit "service.json" to reflect 192.168.1.5. but do i have to change anything in appsettings.json?

or did i understand on how this works?  my goal is to save/copy all files from ftp to my Windows 2011 server as i have 4 bay 2TB there..

Thanks all in advance.

**Comment by Deee46** [comment]
BTW this is the error i got in logs

2017-12-13 12:17:48.4809 [Program] [1] INFO Starting 1.2.14.0 version utility...
2017-12-13 12:17:48.5121 [Program] [1] ERROR System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at Wikiled.YiScanner.Commands.BaseCommand..ctor(FtpConfiguration ftpConfiguration)
   at Wikiled.YiScanner.Program.Main(String[] args)

**Comment by AndMu** [comment]
Hi, what OS you are using?
I suspect it is some older windows version.
Please install .NET 4.6.2 Framework 
https://www.microsoft.com/en-us/download/details.aspx?id=53345

**Comment by Deee46** [comment]
i am running Windows Server 2011.. looks like the 4.6.2 framework did the trick but after running the .exe i have this screenshot below but i do not see the files being pulled from ftp.. i did not touch any settings aside from the "host name" in service.json so it should copy from to my D drive but no folders or files etc. 

what am i missing? do i have to edit or touch anything in appsettings? Thank you.

![yi](https://user-images.githubusercontent.com/34384266/34012021-0613df20-e0c7-11e7-9c59-83b5cad595a4.PNG)

**Comment by AndMu** [comment]
That's by design as in this mode (monitoring) it will download only new images/videos only (with a small delay). 
In monitoring mode, once service/app started it creates the list of all images on the camera and only downloads new images.
I suppose I could change that, but if you want to download all existing videos you can use command:
Wikiled.YiScanner.exe Download -Cameras=1080i -Hosts=192.168.0.202  -Out=c:\out
In next version, I can add configuration option, which would tell the app to download all existing videos.

**Comment by Deee46** [comment]
@AndMu - all good now. once again thank you and will wait for the next release. how i wish time stamp will be kept when copying but i guess it is what it is..

my Yi watermark is a few hours behind too :-( i guess that's what i get from being cheapo lol..

**Comment by AndMu** [comment]
Added new release.
If you add new option: "All":true 
It will download all images (not downloaded before)
https://github.com/AndMu/YiScanner/releases/tag/v1.2.15

**Comment by Deee46** [comment]
any chance you can fix the logs filling up? i did the all:true is service.json and i got a 6GB log files

![logs](https://user-images.githubusercontent.com/34384266/34359657-9f956d12-ea0e-11e7-9e29-2193cc3eca46.PNG)
