### ISSUE TITLE
Log file size

### ISSUE THREAD

**Issue by Deee46** [AndMu/YiScanner#4]
any fix for this? i used the true:all and log files are taking too much space

![logs](https://user-images.githubusercontent.com/34384266/34359690-e8a68202-ea0e-11e7-9bab-d3e3591fe102.PNG)

**Comment by AndMu** [comment]
Updated logging configuration. Please replace nlog.config with latests (or edit)
https://github.com/AndMu/YiScanner/blob/master/src/YiScanner/nlog.config

**Comment by Deee46** [comment]
thank you. its working now with a 100MB log file size.

my other issue now is "Archive": 2, doesn't seem to work. it should delete older files after 2 days correct? but i still have all the videos from day 1 i ran yiscanner.

**Comment by AndMu** [comment]
As I changed the format of the log file name, it will not delete previous version files. But from now on it should keep maximum 100mb and 2 files. Feel free to delete them manually.

**Comment by Deee46** [comment]
im talking about the archive:2 in service.sjson not log files, it should delete all videos older than 2 days correct?

**Comment by AndMu** [comment]
Yes it should.
Archiving runs once per day and should delete files older than 2 days.
Do you see any errors in log file?
Or line Archiving...?

**Comment by Deee46** [comment]
i did use the warn instead of info, will get back to you tomorrow to see if there are any errors etc but mine is not deleting old files.

**Comment by AndMu** [comment]
To be fair I am a little surprised by your log file size. My service is not producing more than 1mb per day.
Either you are scanning very frequently cameras, or I don't really know how to explain that. Could you provide sample of log file. Why it is so large?
And I will double check archiving

**Comment by Deee46** [comment]
my log file is below.. it is now just 536KB after changing it to "warn" but it looks like there is a lot of errors.

https://drive.google.com/open?id=1kPhrSPCXxD9QhrEzQ4zq6yQrZac7_RVS

**Comment by AndMu** [comment]
Can you share your service configuration file? Also you have single service running?

**Comment by Deee46** [comment]
{
  "Scan": 30,
  "Cameras": "Yi1080P",
  "Hosts": "192.168.1.10",
  "Archive": 2,
  "All": true,
  "Out": "C:/"
}

and yes i only have 1 service running "yiscanner service"..

**Comment by AndMu** [comment]
I released bug fix in 1.2.18
https://github.com/AndMu/YiScanner/releases/edit/v1.2.18

That should fix your log file size issue.
Which also (I hope) is related to archiving issue.
