### ISSUE TITLE
Where is the .exe ? :)

### ISSUE THREAD

**Issue by nicolasplanchon** [AndMu/YiScanner#5]
Hi, everything in the title !

A lot of great changes, but how to run the scanner please ? ;)

**Comment by AndMu** [comment]
You can download latest from releases:
https://github.com/AndMu/YiScanner/files/1593330/YiScanner.1.2.18.Zip

**Comment by nicolasplanchon** [comment]
Yep but there is not the .exe in this .zip unfortunately

________________________________
De : Andrius Mudinas <notifications@github.com>
Envoyé : mardi 9 janvier 2018 00:20:23
À : AndMu/YiScanner
Cc : PLANCHON Nicolas; Author
Objet : Re: [AndMu/YiScanner] Where is the .exe ? :) (#5)


You can download latest from releases:
https://github.com/AndMu/YiScanner/files/1593330/YiScanner.1.2.18.Zip

**Comment by AndMu** [comment]
![image](https://user-images.githubusercontent.com/1674086/34715319-16c4ed7a-f524-11e7-9c9c-0c04772aa6d3.png)

**Comment by nicolasplanchon** [comment]
Sounds perfect !
So sorry, it wasn't in my download yesterday evening :/
