### ISSUE TITLE
How to add code ?

### ISSUE THREAD

**Issue by nicolasplanchon** [AndMu/YiScanner#6]
Hi Andrius,
After collecting data from the camera, I wish I could run a .py to analyze my image.

Do you know how may automate this task: run script.py with pparameter "image.jpg" just downloaded please ? 

Thanks in advance,
Nicolas.

**Comment by AndMu** [comment]
As I understand you would like to request a new feature. Execute something on each downloaded image?
I think I could add that. What exactly you are trying to do with the image? Maybe I could simply add that.

**Comment by nicolasplanchon** [comment]
Yep I want to run a python script for every image I download. In my python script there will be only one parameter: the path to to the video.

**Comment by AndMu** [comment]
I will add that in next version. I think it will be ready until the end of the week.

**Comment by nicolasplanchon** [comment]
That sounds crazy!!

________________________________
De : Andrius Mudinas <notifications@github.com>
Envoyé : mercredi 10 janvier 2018 13:13:14
À : AndMu/YiScanner
Cc : PLANCHON Nicolas; Author
Objet : Re: [AndMu/YiScanner] How to add code ? (#6)


I will add that in next version. I think it will be ready until the end of the week.

**Comment by AndMu** [comment]
new version to support actions: https://github.com/AndMu/YiScanner/releases/tag/v1.3.4

**Comment by AndMu** [comment]
Payload is not in use in this version.  It will be for Rest services like IFTTT.
In your case you should change  "Cmd": "python script.py %1",

**Comment by nicolasplanchon** [comment]
Yes okep and if this script.py needs a variable which is the last pic downloaded as a parameter, you have a trick ?

**Comment by AndMu** [comment]
%1 will be replaced by file name (internally in program)

**Comment by nicolasplanchon** [comment]
yes okep I understand the way you want to run this!
I try asap, a huge thanks!
