### ISSUE TITLE
ERROR Newtonsoft.Json.JsonReaderException: Bad JSON escape sequence

### ISSUE THREAD

**Issue by nicolasplanchon** [AndMu/YiScanner#7]
Hello,
I have an error in my logs:

> 2018-01-10 21:20:10.7348 [Program] [1] ERROR Newtonsoft.Json.JsonReaderException: Bad JSON escape sequence: \U. Path 'Out', line 8, position 14.
   à Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   à Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   à Newtonsoft.Json.JsonTextReader.ReadAsString()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   à Wikiled.YiScanner.Program.StartService(String directory, FtpConfiguration ftpConfiguration)
   à Wikiled.YiScanner.Program.Main(String[] args)

The outh path seems to suffer problem a type problem, however I don't really understand what matters.

Here is my config:

![image](https://user-images.githubusercontent.com/33055289/34793752-ba1f18dc-f64c-11e7-99b6-23135b7531ef.png)

Thanks in advance,
Nicolas.

**Comment by AndMu** [comment]
Replace path with c:/Users/noico....

**Comment by nicolasplanchon** [comment]
Still the same error with this config:
![image](https://user-images.githubusercontent.com/33055289/34795763-a4d36ae4-f653-11e7-9839-caef705aaf09.png)

**Comment by AndMu** [comment]
But you haven't changed as I suggested - backslash with forward slash

**Comment by nicolasplanchon** [comment]
Oh yes sorry, I had forgotten I was working with this fuckin windows lol...

A brand new bug for you lol:

> 2018-01-10 22:30:14.3432 [FtpDownloader] [10] ERROR System.IO.FileNotFoundException: Impossible de charger le fichier ou l'assembly 'Accord.Video.FFMPEG.dll' ou une de ses dépendances. Le module spécifié est introuvable.
Nom de fichier : 'Accord.Video.FFMPEG.dll'
   à Wikiled.YiScanner.Destinations.PictureFileDestination.<Transfer>d__3.MoveNext()
   à System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   à Wikiled.YiScanner.Destinations.PictureFileDestination.Transfer(VideoHeader header, Stream source)
   à Wikiled.YiScanner.Client.FtpDownloader.<ProcessFile>d__9.MoveNext()

**Comment by AndMu** [comment]
I think this one is caused by missing redistributable files on your system.
Please install (x86 version):
https://www.microsoft.com/en-gb/download/details.aspx?id=48145

**Comment by nicolasplanchon** [comment]
Yep indeed, it solved this issue !

Another feedback:

[swscaler @ 09aa28c0] deprecated pixel format used, make sure you did set range correctly

**Comment by Lavyk** [comment]
Replace all of \ with \\
