### ISSUE TITLE
Time out error

### ISSUE THREAD

**Issue by nicolasplanchon** [AndMu/YiScanner#8]
> 2018-01-10

 23:52:26.9467 [MonitoringInstance] [22] [ERROR] System.TimeoutException: Timed out trying to read data from the socket stream!
   à FluentFTP.FtpSocketStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   à FluentFTP.FtpDataStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   à FluentFTP.FtpSocketStream.<ReadAllLines>d__66.MoveNext()
   à FluentFTP.FtpClient.GetListing(String path, FtpListOption options)
   à Wikiled.YiScanner.Client.FtpDownloader.<Retrieve>d__10.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Wikiled.YiScanner.Client.FtpDownloader.<Retrieve>d__10.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Wikiled.YiScanner.Client.FtpDownloader.<Download>d__8.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Wikiled.YiScanner.Monitoring.MonitoringInstance.<Download>d__10.MoveNext()
2018-01-10 23:52:52.3172 [MonitoringInstance] [43] [ERROR] System.TimeoutException: Timed out trying to read data from the socket stream!
   à FluentFTP.FtpSocketStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   à FluentFTP.FtpSocketStream.ReadLine(Encoding encoding)
   à FluentFTP.FtpClient.GetReply()
   à FluentFTP.FtpClient.Execute(String command)
   à FluentFTP.FtpClient.GetListing(String path, FtpListOption options)
   à Wikiled.YiScanner.Client.FtpDownloader.<Retrieve>d__10.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

**Comment by nicolasplanchon** [comment]
Is this because after an inactivity time we get disconnected from the ftp servor?

**Comment by AndMu** [comment]
That is more about your network and how stable is your connection to the camera.
It is possible to increase timeout, however if application is downloading video/images and you are getting a warning only occasionally, I would ignore it.
